# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMEHV9DlaAxkAwRSnUlQ5kzamDD-YBBr
"""

Touched bt 2 user2

p= 'hello'
print(p)


name = '임서연'
number = 201904479
major = '컴퓨터전자시스템'
